### ISSUE TITLE
CRS-related warning in autoplot seems incoherent

### ISSUE THREAD

**Issue by alexanderbrenning** [mlr-org/mlr3spatiotempcv#148]
`autoplot` throws the following warning when some of the resampling methods are applied to the `ecuador` task (see application of methods `"spcv_disc"` and `"spcv_block"` in the manuscript):

> CRS not set, transforming to WGS84 (EPSG: 4326).

This doesn't seem to make sense, as a transformation to WGS84 is not possible when the source CRS is unknown. As far as I can see the `ecuador` dataset and task contains only UTM coordinates, not even lat/lon, therefore it is also not possibly to just assume that WGS84 is present or to guess which UTM zone is applicable.
Just a minor issue, but potentially confusing...

**Comment by pat-s** [comment]
It seems you are not on the latest revision, please do a `git pull`. I removed this warning and changed the CRS handling in `autoplot` in #144 and just double-checked that there is no instance left in both the `paper` and `main` branches.

It might be also worth checking if you are on the latest revision with respect to PR #147.

**Comment by jannes-m** [comment]
Alex is right in noting that the Ecuador dataset is using UTM coordinates (CRS:32717), see also https://github.com/mlr-org/mlr3book/pull/251.

**Comment by pat-s** [comment]
@jannes-m The mlr3book is using the CRAN version which does not have the changes applied in #144 yet.

I am not sure if we are confusing things here:

- the `ecuador` task is using CRS:32717. This seems fine to me. What is possibly wrong here?
- The transformation to CRS:4326 in `autoplot` does not happen anymore since #144, the CRS from the task is taken

To me it seems that

- Alex tested on an old version
- You are referring to the mlr3book version which uses the CRAN version 4.1.0 which does not contain #144 yet

Please correct me I am mistaken :)

**Comment by jannes-m** [comment]
I didn't know that there was an open PR which has not yet beem merged into the book. I only came across `data_sf = sf::st_as_sf(ecuador, coords = c("x", "y"), crs = 4326)` in the book which just assigns the wrong CRS. So, if https://github.com/mlr-org/mlr3spatiotempcv/pull/144 is addressing this by using 32717, forget about my PR -:)

**Comment by alexanderbrenning** [comment]
I installed the most recent release of R (4.1.0) and all packages, including mlr3spatiotempcv from github, but the warning still comes up. It's probably not important, as long as you @pat-s don't get the warning when you knit the paper.

**Comment by alexanderbrenning** [comment]
@pat-s 

> It might be also worth checking if you are on the latest revision with respect to PR #147.

I don't think PR #147  has much to do with the package version. That one was mainly about the paper but then of course package users might also benefit from a coherent terminology....

**Comment by alexanderbrenning** [comment]
argh! Death to the chunk cache! Now something else broke (in the manuscript) so I can't confirm that the message actually disappeared. @pat-s I the paper code might need some fixing, it currently fails on my computer in line 566 with "Error: Objects of type ResamplingCustomCV/Resampling/R6 not supported by autoplot."...

**Comment by alexanderbrenning** [comment]
Warning is gone now. Thanks.

**Comment by pat-s** [comment]
> I don't think PR #147 has much to do with the package version. That one was mainly about the paper but then of course package users might also benefit from a coherent terminology....

If you install from GH you'll get the main branch by default. The `paper` branch should always be on sync with the main branch but there is no full guarantee (I might miss to sync at some point). So it makes sense to specifically install the `paper` branch state to be up-to-date using `remotes::install_github("mlr-org/mlr3spatiotempcv@paper")`.

My comment regarding #147 was just a positive minded hint because I saw the danger of a missed pull and a review by you on an outdated revision.

> argh! Death to the chunk cache! 

Yes, cache can be tricky. It makes sense to clear the cache from time to time, especially if there have been moderate changes to the underlying code.

> it currently fails on my computer in line 566 with "Error: Objects of type ResamplingCustomCV/Resampling/R6 not supported by autoplot."...

I'll look into it, thanks.
