### ISSUE TITLE
sf object no longer accepted by TaskClassifST

### ISSUE THREAD

**Issue by jannes-m** [mlr-org/mlr3spatiotempcv#203]
### Description

Dear mlr3spatiotempcv team, 
thanks again for this fantastic package. After using the latest release, we ran into following [issue](https://github.com/Robinlovelace/geocompr/issues/816).
Basically, `TaskClassifST`  and `TaskRegrST` no longer accept sf objects as backends. I suppose this is not intented, at least the [Getting Started  Article](https://mlr3spatiotempcv.mlr-org.com/articles/mlr3spatiotempcv.html) still uses sf objects as backend inputs. Interestingly, `as_task_classif_st()` accepts sf objects.

### Reproducible example

``` r
library("mlr3spatiotempcv")
#> Loading required package: mlr3
data_sf = sf::st_as_sf(ecuador, coords = c("x", "y"))

# this does not work:
task = TaskClassifST$new(id = "ecuador_sf", backend = data_sf,
                         target = "slides", positive = "TRUE")
#> Error in .__Task__initialize(self = self, private = private, super = super, : Assertion on 'feature types' failed: Must be a subset of {'logical','integer','numeric','character','factor','ordered','POSIXct'}, but has additional elements {'sfc_POINT'}.

# however, this works:
task = as_task_classif_st(data_sf, id = "ecuador_sf",
                          target = "slides", positive = "TRUE")
```

<sup>Created on 2022-06-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by pat-s** [comment]
Thanks for reporting!

This should not happen, `TaskClassifST$new()` should in general accept `sf` objects.
In {mlr3} we are moving towards using the `as_<something>` converters everywhere instead of the R6 notation, so using/switching to `as_task_classif_st()` is perfectly fine right now.
But you can also stay with the old one if you think this approach is more descriptive than using the converters.

I just see that https://mlr3spatiotempcv.mlr-org.com/articles/mlr3spatiotempcv.html does not evaluate the code (for no real reason acutally, otherwise this would have been caught earlier).

I'll fix this in the next days and issue a new patch release!
