### ISSUE TITLE
Optimize `mlr_reflections` behavior for package

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3spatiotempcv#26]
Should `TaskClassifST` and friends have entries in `mlr_reflections$task_types`?

**Comment by pfistfl** [comment]
In `zzz.R`; `coordinates` are properties belonging to `regr` and not something like `regrst`. 
(Which does not break anything, but how do I now look up which properties belong to a given Task. 
Via walking up the dependency chain?

**Comment by pat-s** [comment]
> Should TaskClassifST and friends have entries in mlr_reflections$task_types?

Yes, thanks!

> In zzz.R; coordinates are properties belonging to regr and not something like regrst.
> (Which does not break anything)
> But how do I now look up which properties belong to a given Task.
> Via walking up the dependency chain?

I see. Maybe instead of returning `$regr` and `$classif`, `mlr_reflections` could return the  `$task` property, i.e. `TaskClassif` or `TaskClassifST`.
Then it would become more clear to what (sub-class) the `task_col_rules` belong to (assuming we add new ones for ClassifST and ClassifRegr).

```r
mlr_reflections$task_col_roles
$regr
[1] "feature"     "target"      "name"        "order"       "stratum"     "group"      
[7] "weight"      "coordinates"

$classif
[1] "feature"     "target"      "name"        "order"       "stratum"     "group"      
[7] "weight"      "coordinates"
```

I think it makes sense to add a unique `task_type` and also add the special col roles to that.
So that one can have a clear list of the current task types available and its specific `task_col_roles`.

@mllg What do you think of returning `$task` instead of `$type` when printing `mlr_reflections$task_col_roles`? Haven't yet looked in detail but maybe one needs to swap the slot of how the `col_roles` are stored within the dict?

What I want is this

```r
mlr_reflections$task_col_roles
$TaskRegr
[1] "feature"     "target"      "name"        "order"       "stratum"     "group"      
[7] "weight"      "coordinates"

$TaskClassif
[1] "feature"     "target"      "name"        "order"       "stratum"     "group"      
[7] "weight"      "coordinates"
```

because when I would add a new `task_type` called `regrst` this is really confusion to read. I don't think `regr_st` is that much better? I'd rather prefer `TaskRegrST`.
